# When all is done
rule done:
    input:
        'data/output.csv'
    shell:
        'echo Pipiline complete!'

# transforme fasta DB to diamond format
rule transform_fastaDB_to_diamondDB:
    input:
        'data/swissprot'
    output:
        'data/swissprotDB.dmnd'
    shell:
        './diamond makedb --in {input} -d {output}'

# use blastx with DNA genome data on formated protein DB
rule use_diamonds_blastx:
    input:
        diamond_db = 'data/swissprotDB.dmnd',
        genome = 'data/U00096.2.fasta'
    output:
        'data/output.tsv'
    shell:
        './diamond blastx -q {input.genome} -d {input.diamond_db} -o {output} --very-sensitive'

# change tsv to csv
rule transform_tsv_to_csv:
    input:
        'data/output.tsv'
    output:
        'data/output.csv'
    shell:
        "sed 's/\t/,/g' {input} > {output}.csv"
